
#include <p16f690.inc>
 __CONFIG _FOSC_EXTRCCLK & _WDTE_OFF & _PWRTE_OFF & _MCLRE_OFF & _CP_ON & _CPD_ON & _BOREN_OFF & _IESO_OFF & _FCMEN_ON ;configuration of conifguration pins of the pic16f690, it is generated by the MPLAB X configuration generation
RES_VECT  CODE    0x0000            ; processor reset vector 
  GOTO    START                   ; go to beginning of program
ORG 0X0008
BTFSC  INTCON,T0IF
GOTO TMRROUTINE
GOTO INTROUTINE
RETFIE
  ORG 0X100
 ;Implementation of lookup table for storing the sequence of Seven segment display
MAIN_PROG CODE                      ; let linker place main program
START
 VAR EQU 0X31			    ;Assigning variable name for holding value 
 VAR2 EQU 0X32
 TEMP EQU 0X33;Assigning variable name for holding value 
 hundreds equ 0x20	
 tens equ 0x21    
 units equ 0x22 
 hundreds1 equ 0x23	
 tens1 equ 0x24    
 units1 equ 0x25 
 MOVLW 0X01
 MOVWF TEMP
BCF STATUS, RP0 ;Bank 2
BSF STATUS, RP1 ;
MOVLW 0x00 ;
MOVWF EEADR ;Data Memory Address to write
BCF STATUS, RP0 ;Bank 2
BCF STATUS, RP1 ;
 BSF INTCON,GIE			    ;ENABLE GLOBAL INTERRUPT
 BSF INTCON,INTE		    ;ENABLE EXTERNAL INTERRUPT
 ;SETTING PORTC
 BCF STATUS,RP0			    
 BCF STATUS,RP1
 CLRF PORTC
 BSF STATUS,RP1
 MOVLW B'10000000'
 MOVWF ANSEL
 BSF STATUS,RP0
 BCF STATUS,RP1
 MOVLW 0X00
 MOVWF TRISC
 BCF STATUS,RP0
;Setting PORTB
 BCF STATUS,RP0
 BCF STATUS,RP1
 CLRF PORTB
 BSF STATUS,RP0
 MOVLW 0X00
 MOVWF TRISB
 BCF STATUS,RP0
 ;////////////////////
 CLRF VAR		    ;Clearing the variable VAR for storing units
 CLRF VAR2		    ;Clearing the variable for storing tens
 ;SETTING PORTA,RA2 AS INPUT FOR INTERRUPT
 BCF STATUS,RP0
 BCF STATUS,RP1
 BCF PORTA,RA2
 BSF STATUS,RP1
 CLRF ANSEL		    ;SET I/O AS DIGITAL
 BSF STATUS,RP0
 BCF STATUS,RP1
 MOVLW 0X0F
 MOVWF TRISA                ;PORTA.RA2 External interrupt pin as input
 BCF STATUS,RP0
 ;SETTING ADC MODULE FOR ANALOG TO DIGITAL CONVERSION OF TEMPERATURE SENSOR SIGNAL
 BSF STATUS,RP0
 BCF STATUS,RP1
 MOVLW B'01110000'
 MOVWF ADCON1
 BSF TRISA,0
 BCF STATUS,RP0
 BSF STATUS,RP1
 BSF ANSEL,0
 BCF STATUS,RP1
 BCF STATUS,RP0
 MOVLW B'10000001'
 MOVWF ADCON0
 CALL S_DELAY
 CALL S_DELAY
 ;////////////////////////////////////////////////////////////////////////
 ;CONFIGURE THE TIMER1 FOR UPGRADATION OF TEMPERATURE VALUE
 MOVLW B'10000111'
 BSF STATUS,RP0
 BCF STATUS,RP1
 MOVWF OPTION_REG
 MOVLW 0X00
 BCF STATUS,RP0
 BCF STATUS,RP1
 MOVWF TMR0
 MOVLW B'10110000'
 MOVWF INTCON
 ;////////////////////////////////////////////////////////////////////////
 ;Seven segment display code (comparing variable and assigning value to PORTC)
 SSD1
  BTFSC PORTA,RA4
  CALL DATA_READING
  BCF PORTB,RB6
  BSF PORTB,RB7
  MOVF units,W
  CALL LUKUP
  MOVWF PORTC
  ;DISPLAY MULTIPLEXING TECHNIQUE IS APPLIED HERE
  CALL S_DELAY
  BSF PORTB,RB6
  BCF PORTB,RB7
  MOVF tens,W
  CALL LUKUP
  MOVWF PORTC
  CALL S_DELAY
  GOTO SSD1
  ;/////////////////////////////////////////////////////
  ;Short delay routine
  ;////////////////////////////////////////////////////
 DATA_READING
 ;BCF INTCON,GIE
 BCF STATUS,RP0
 BSF STATUS,RP1
 CLRF EEADR
 REPEAT
 BCF STATUS,RP0
 BSF STATUS,RP1
 INCF EEADR,F
 MOVLW 0X04
 SUBWF EEADR,W
 BCF STATUS,RP0
 BCF STATUS,RP1
 BTFSC STATUS,Z
  RETURN
 ;BSF INTCON,GIE
 BSF STATUS,RP0
 BSF STATUS,RP1
 BCF EECON1,07
 BSF EECON1,0
 BSF STATUS,RP1
 BCF STATUS,RP0
 MOVF EEDAT,W
 BCF STATUS,RP0
 BCF STATUS,RP1
  hex2bcd     movwf   units1                   
             movlw   d'0'                    
             movwf   tens1                    
             movwf   hundreds1                
 h2b_xxx     movlw   d'100'  
             subwf   units1,w     
             btfss   STATUS,C  
             goto    h2b_xx   
             movwf   units1      
             incf    hundreds1  
             goto    h2b_xxx   
 h2b_xx      movlw   d'10'   
             subwf   units1,w          
             btfss   STATUS,C  
             goto    h2b_x   
             movwf   units1       
             incf    tens1   
             goto    h2b_xx   
 h2b_x   
 BTFSC PORTA,RA4
  GOTO $-1 
 SECONDARY
  BTFSC PORTA,RA4
  GOTO REPEAT
  BCF PORTB,RB6
  BSF PORTB,RB7
  MOVF units1,W
  CALL LUKUP
  MOVWF PORTC
  ;DISPLAY MULTIPLEXING TECHNIQUE IS APPLIED HERE
  CALL S_DELAY
  BSF PORTB,RB6
  BCF PORTB,RB7
  MOVF tens1,W
  CALL LUKUP
  MOVWF PORTC
  CALL S_DELAY
  GOTO SECONDARY
 S_DELAY
 count equ 0x40
 movlw 0x0F
 movwf count
 LOOP DECFSZ count,F
 GOTO LOOP  
 RETURN
 LUKUP
 ADDWF PCL,F
 RETLW 0XC0
 RETLW 0XF9
 RETLW 0XA4
 RETLW 0XB0
 RETLW 0X99
 RETLW 0X92
 RETLW 0X82
 RETLW 0XF8
 RETLW 0X80
 RETLW 0X90
 TMRROUTINE
 BSF ADCON0,GO
 BCF STATUS,RP1
 BTFSC ADCON0,GO
 GOTO $-1
 BSF STATUS,RP0
 MOVF ADRESL,W
 BCF STATUS,RP0
 MOVWF VAR
 BCF STATUS,C
 RRF VAR,F
 MOVLW 0X0A
 SUBWF VAR,W
  MOVWF VAR
; //binary to BCD conversion
 hex12bcd     movwf   units                   
             movlw   d'0'                    
             movwf   tens                    
             movwf   hundreds                
 h12b_xxx     movlw   d'100'  
             subwf   units,w     
             btfss   STATUS,C  
             goto    h12b_xx   
             movwf   units      
             incf    hundreds  
             goto    h12b_xxx   
 h12b_xx      movlw   d'10'   
             subwf   units,w          
             btfss   STATUS,C  
             goto    h12b_x   
             movwf   units       
             incf    tens   
             goto    h12b_xx   
 h12b_x   
            BCF INTCON,T0IF
;	    MOVF tens,W
;	    MOVF units,W
            RETFIE
INTROUTINE
MOVF TEMP,W
BCF STATUS, RP0 ;Bank 2
BSF STATUS, RP1 
MOVWF EEADR
MOVLW 0X03
SUBWF EEADR,W
BCF STATUS,RP0
BCF STATUS,RP1 
BTFSS STATUS,Z
GOTO RTN
BCF INTCON,INTF
BCF STATUS, RP0 ;Bank 2
BSF STATUS, RP1 
CLRF EEADR
RETFIE
RTN
MOVF VAR,W
BSF STATUS,RP1
BCF STATUS,RP0
MOVWF EEDAT ;Data Memory Value to write
BSF STATUS,RP1
BSF STATUS, RP0 ;Bank 3
BCF EECON1, EEPGD ;Point to DATA memory
BSF EECON1, WREN ;Enable writes
MOVLW 0x55 ;
MOVWF EECON2 ;Write 55h
MOVLW 0xAA ;
MOVWF EECON2 ;Write AAh
BSF EECON1, WR ;Set WR bit to begin write
BCF INTCON,INTF
BSF STATUS,RP1
BCF STATUS,RP0
INCF EEADR,F
MOVF EEADR,W
BSF STATUS,RP0
BSF STATUS,RP1
BCF EECON1, WREN ;Disable writes
BCF STATUS,RP0
BCF STATUS,RP1
MOVWF TEMP
RETFIE
END